# Ä�Ă¡p Ă¡n cá»§a 20 hĂ¬nh captcha, sinh bá»Ÿi tools/CaptchaGenerator.java
captcha01=V5DBN2
captcha02=K2U3YZ
captcha03=DVQA7Q
captcha04=PAVJ82
captcha05=W2RBBG
captcha06=TQ9E7N
captcha07=B34XUW
captcha08=RUVV9F
captcha09=GJEZVE
captcha10=UEKN8V
captcha11=G9B8B2
captcha12=MHN7U7
captcha13=DJX5EE
captcha14=64QYVY
captcha15=MVJCUH
captcha16=8SPPJC
captcha17=2CWMDZ
captcha18=WK5MRM
captcha19=FZZBD4
captcha20=3QH6SS
