spring.application.name=duan-1-9
server.port=8083

# Tắt cache để sửa file HTML xong chỉ cần refresh trình duyệt
spring.thymeleaf.cache=false

welcome.message=Hello Thymeleaf
error.message=First Name & Last Name is required!
